import os
import time
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DONE_FOLDER = os.path.join(BASE_DIR, "Done")
BRIEFINGS_FOLDER = os.path.join(BASE_DIR, "Briefings")

os.makedirs(BRIEFINGS_FOLDER, exist_ok=True)

def generate_ceo_briefing():
    today = datetime.now().strftime("%Y-%m-%d")
    briefing_file = os.path.join(BRIEFINGS_FOLDER, f"{today}_CEO_Briefing.md")
    
    # Count completed tasks
    done_tasks = os.listdir(DONE_FOLDER) if os.path.exists(DONE_FOLDER) else []
    
    briefing = f"""# Monday Morning CEO Briefing
## Date: {today}

## Executive Summary
AI Employee system is running. Weekly report generated automatically.

## Completed Tasks This Week
Total tasks completed: {len(done_tasks)}

"""
    for task in done_tasks:
        briefing += f"- {task}\n"
    
    briefing += f"""
## System Status
- Watcher: Running
- Orchestrator: Running  
- Approval Workflow: Active

## Generated
*Generated by Personal AI Employee at {datetime.now().strftime("%H:%M:%S")}*
"""
    
    with open(briefing_file, "w") as f:
        f.write(briefing)
    
    print(f"CEO Briefing generated: {briefing_file}")
    return briefing_file

print("Generating CEO Briefing...")
generate_ceo_briefing()
print("Done!")